### ISSUE TITLE
Enviar mensagem de resposta em Status Recebido

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wppconnect#809]
Note: Envia um COMENTÁRIO em um status RECEBIDO (que outra pessoa postou).

- [ ] Feature #676 - Add função "sendStickerCommentInStatusReceived" => Envia um comentário de STICKER.
- [ ] Feature #675 - Add função "sendPttCommentInStatusReceived" => Envia um comentário de ÁUDIO PTT.
- [ ] Feature #674 - Add função "sendTextCommentInStatusReceived" => Envia um comentário de TEXTO.
- [ ] Feature - Add função "sendGifCommentInStatusReceived" => Envia um comentário de GIF.

**Comment by icleitoncosta** [comment]
Olá, utilizando a última versão do WAJS (2.11.0), é só você enviar a mensagem com send file ou sendText e passar o parâmetro quotedMsg: msgId


Ex:

```
client.sendText("id", "mensagem" { quotedMsg:"552234443423_78866766 } );
```

**Comment by icleitoncosta** [comment]
> Olá, utilizando a última versão do WAJS (2.11.0), é só você enviar a mensagem com send file ou sendText e passar o parâmetro quotedMsg: msgId
> 
> 
> Ex:
> 
> ```
> client.sendText("id", "mensagem" { quotedMsg:"552234443423_78866766 } );
> ```
> 

No caso, no quotedMsg você irá passar o statusId
